#pragma once

#define STUB_RC "res\\stub.rc"
#define EDIT_RC "res\\bat2exe.rc"
#define STUB_RES "obj\\stub.res"
#define EDIT_RES "obj\\bat2exe.res"
#define RC_CMD "rc.exe -nologo -fo" STUB_RES " "
#define RC_EDIT_CMD "rc.exe -nologo -fo" EDIT_RES " "
#define RC_NO_COMPRESS "-dNO_COMPRESSION=1 "
#define RC_EXEC_LOCAL "-dEXEC_LOCAL=1 "
#define STUB_OBJ "obj\\stub.obj"
#define EDIT_OBJ "obj\\bat2exe.obj"
#define CL_CMD "cl.exe -nologo -Fo" STUB_OBJ " -Ires -Isrc -Iinclude "
#define CL_EDIT_CMD "cl.exe -nologo -Fo" EDIT_OBJ " -Ires -Isrc -Iinclude "
#define CL_NO_COMPRESS "-DNO_COMPRESSION=1 "
#define CL_EXEC_LOCAL "-DEXEC_LOCAL=1 "
#define STUB_C "src\\stub.c"
#define EDIT_C "src\\bat2exe.c"
#define CL_END STUB_C " " STUB_RES " -link -LIBPATH:lib -LTCG -OPT:REF -OPT:ICF"
#define CL_EDIT_END EDIT_C " " EDIT_RES " -link -LIBPATH:lib -LTCG -OPT:REF -OPT:ICF"